name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  test:
    name: run android unit tests
    runs-on: ubuntu-latest

    steps:
      - name: set up JDK 11.0.12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.12
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/checkout@v1
      - name: Checkout secrets
        uses: actions/checkout@v2
        with:
          repository: 'herowio/herow-api-secrets'
          token: ${{ secrets.PAT_READ_PRIVATE_REPO }}
          path: secrets
      - name: copy platform-secrets.properties
        run: cp secrets/platform-secrets.properties ./platform-secrets.properties
      - name: unit tests
        run: ./gradlew testDebugUnitTest
