name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  test:
    name: run android unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout secrets
        uses: actions/checkout@v2
        with:
          repository: 'herowio/herow-api-secrets'
          token: ${{ secrets.PAT_READ_PRIVATE_REPO }}
          path: secrets
      - name: copy platform-secrets.properties
        run: cp secrets/platform-secrets.properties ./platform-secrets.properties
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: unit tests
        run: bash ./gradlew clean testDebugUnitTest 
