name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  test:
    name: run android unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: add platform_secrets 
        env:
            PLATFORM_SECRETS: ${{ secrets.PLATFORM_SECRETS }}
        run: echo $PLATFORM_SECRETS > platform-secrets.properties
      - name: unit tests
        run: bash ./gradlew clean test --stacktrace
